---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istiod
  namespace: argocd
spec:
  generators:
    - clusters: {} 
  template:
    metadata:
      name: 'istiod-{{ name }}'
    spec:
      project: default
      source: 
        repoURL: https://github.com/ky-rafaels/istio-controlplane.git
        targetRevision: main
        path: helm/1.18.3/istiod
        helm:
          releaseName: istiod
          ignoreMissingValueFiles: true
          parameters:
            - name: cluster
              value: "{{ name }}"
          valueFiles:
            - values.yaml
            - values-{{ name }}.yaml
      destination:
        name: "{{ name }}"
        namespace: 'istio-system'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      ignoreDifferences:
        - group: admissionregistration.k8s.io
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
          jsonPointers:
            - /webhook/0/failurePolicy
