apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../base"

patchesJson6902:
- target:
    version: v1alpha1
    name: "istio.*"
    kind: Application
  patch: |-
    - op: replace
      path: /spec/source/targetRevision
      value: 1.16.1

patchesStrategicMerge: 
- |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: istio-ingress
      namespace: argocd
    spec:
      source:
        helm:
          values: |
            name: istio-ingressgateway-staging
            revision: staging
            service:
              type: None
            labels:
              istio: ingressgateway
              istio.io/rev: staging
            annotations:
              proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
- |
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: istiod
      namespace: argocd
    spec:
      source:
        helm:
          values: |
            revision: staging
            global:
              meshID: mesh1
              multiCluster:
                clusterName: cluster1
              network: network1
              hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
              tag: 1.16.1-solo
            meshConfig:
              accessLogFile: /dev/stdout
              accessLogEncoding: JSON
              protocolDetectionTimeout: 5s
              defaultConfig:
                holdApplicationUntilProxyStarts: true
                proxyMetadata:
                  ISTIO_METADATA_DNS_CAPTURE: "true"
                gatewayTopology:
                  forwardClientCertDetails: FORWARD_ONLY
              outboundTrafficPolicy:
                mode: ALLOW_ANY
            env:
              PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES: "false"
              PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
- |
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        istio: ingressgateway
        revision: staging
      name: istio-ingressgateway
      namespace: istio-ingress
    spec:
      selector:
        istio: ingressgateway
        istio.io/rev: staging

nameSuffix: "-staging"