name: istio-ingress-private
revision: 1-17
service:
  type: LoadBalancer
  # type: NodePort
labels:
  istio: ingressgateway
  gateway-type: private
  istio.io/rev: 1-17
annotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'