name: ""
revision: 1-16
service:
  type: LoadBalancer 
  # type: NodePort
labels:
  istio: eastwestgateway
  istio.io/rev: 1-16
  app: eastwestgateway
annotations:
  proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'