---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod-1-15
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.15.4
      helm:
        valueFiles:
        - $values/helm/1.15.4/values/istiod.yaml
      chart: istiod
    - repoURL: https://github.com/ky-rafaels/istio-controlplane.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
