---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-eastwest-1-18
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-eastwest
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.18.3
      helm:
        valueFiles:
        - $values/helm/1.18.3/values/istio-eastwest.yaml
      chart: gateway
    - repoURL: https://github.com/ky-rafaels/istio-controlplane.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: istio-ingressgateway
#     istio: eastwestgateway
#     topology.istio.io/network: ""
#   name: istio-eastwest-1-18
#   namespace: istio-eastwest
# spec:
#   ports:
#   - name: status-port
#     port: 15021
#     protocol: TCP
#     targetPort: 15021
#   - name: tls
#     port: 15443
#     protocol: TCP
#     targetPort: 15443
#   - name: https
#     port: 16443
#     protocol: TCP
#     targetPort: 16443
#   - name: tcp-istiod
#     port: 15012
#     protocol: TCP
#     targetPort: 15012
#   - name: tcp-webhook
#     port: 15017
#     protocol: TCP
#     targetPort: 15017
#   selector:
#     app: istio-ingressgateway
#     istio: eastwestgateway
#     revision: canary
#     topology.istio.io/network: "" 
#   type: LoadBalancer