# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: istio-ingressgateway
#     istio: ingressgateway
#   name: istio-ingressgateway
#   namespace: istio-gateways
# spec:
#   ports:
#   - name: http2
#     port: 80
#     protocol: TCP
#     targetPort: 8080
#   - name: https
#     port: 443
#     protocol: TCP
#     targetPort: 8443
#   selector:
#     app: istio-ingressgateway
#     istio: ingressgateway
#     revision: 1-17
#   type: LoadBalancer
---
apiVersion: admin.gloo.solo.io/v2
kind: GatewayLifecycleManager
metadata:
  name: cluster2-ingress
  namespace: gloo-mesh
spec:
  installations:
    - clusters:
      - name: cluster2
        activeGateway: false
      gatewayRevision: 1-17
      istioOperatorSpec:
        profile: empty
        hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
        tag: 1.17.2-solo
        # values:
        #   gateways:
        #     istio-ingressgateway:
        #       customService: true
        components:
          ingressGateways:
            - name: istio-ingressgateway
              namespace: istio-gateways
              enabled: true
              label:
                istio: ingressgateway