revision: 1-15
global:
  meshID: mesh1
  multiCluster:
    clusterName: cluster1
  network: network1
  hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
  tag: 1.15.4-solo
meshConfig:
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  protocolDetectionTimeout: 5s
  defaultConfig:
    holdApplicationUntilProxyStarts: true
    proxyMetadata:
      ISTIO_METADATA_DNS_CAPTURE: "true"
    gatewayTopology:
      forwardClientCertDetails: FORWARD_ONLY
  outboundTrafficPolicy:
    mode: ALLOW_ANY
env:
  PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES: "false"
  PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"