name: istio-ingress
revision: canary
service:
  type: LoadBalancer
labels:
  istio: ingressgateway
  istio.io/rev: 1-18
# annotations:
#   proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'