---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-eastwest-1-17
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-eastwest
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.17.2
      helm:
        valueFiles:
        - $values/1.17.2/values/istio-eastwest.yaml
      chart: gateway
    - repoURL: https://github.com/ky-rafaels/istio-controlplane.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true