---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base-1-15
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.15.4
    chart: base
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true