apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: httpbin-istio-route
  namespace: istio-ingress
spec:
  gateways:
  - istio-ingress/primary-gateway
  hosts:
  - httpbin.kyle.consultsolo.net
  http:
  - match:
    - uri:
        prefix: /
    name: httpbin-route
    route:
    - destination:
        host: httpbin.httpbin.svc.cluster.local
        port:
          number: 8000
