---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.16.1
    helm:
      values: |
        revision: 1-16
        global:
          meshID: mesh1
          multiCluster:
            clusterName: cluster1
          network: network1
          hub: us-docker.pkg.dev/gloo-mesh/istio-workshops
          tag: 1.16.1-solo
        meshConfig:
          accessLogFile: /dev/stdout
          accessLogEncoding: JSON
          protocolDetectionTimeout: 5s
          defaultConfig:
            holdApplicationUntilProxyStarts: true
            proxyMetadata:
              ISTIO_METADATA_DNS_CAPTURE: "true"
            gatewayTopology:
              forwardClientCertDetails: FORWARD_ONLY
          outboundTrafficPolicy:
            mode: ALLOW_ANY
        env:
          PILOT_ENABLE_K8S_SELECT_WORKLOAD_ENTRIES: "false"
          PILOT_SKIP_VALIDATE_TRUST_DOMAIN: "true"
    chart: istiod
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true

        # sidecarInjectorWebhook:
        #   templates:
        #     custom: |
        #       spec:
        #         containers:
        #           - name: istio-proxy
        #             env:
        #               - name: POD_UID
        #                 valueFrom:
        #                   fieldRef:
        #                     apiVersion: v1
        #                     fieldPath: metadata.u